// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
package net.extendedpistons.block;

import net.minecraft.block.PistonExtensionBlock;

public class GoldPistonExtention extends PistonExtensionBlock
{
	public GoldPistonExtention(Settings settings) {
		super(settings);
		//TODO Auto-generated constructor stub
	}

 
}