// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
package net.extendedpistons.block;

import net.minecraft.block.PistonHeadBlock;

public class GoldPistonHead extends PistonHeadBlock
{

  public GoldPistonHead(Settings settings) {
    super(settings);
    // TODO Auto-generated constructor stub
  }

 
}