// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
package net.extendedpistons.block;

import net.minecraft.block.PistonBlock;

public class GoldPiston extends PistonBlock {

  public GoldPiston(boolean isSticky, Settings settings) {
    super(isSticky, settings);
    // TODO Auto-generated constructor stub
  }
 
}