// Failed to get sources. Instead, stub sources have been generated by the disassembler.
// Implementation of methods is unavailable.
package net.extendedpistons.block.blockentity;

import net.minecraft.block.entity.PistonBlockEntity;

public class GoldPistonEntity extends PistonBlockEntity {

  public GoldPistonEntity() {

  }
  move
}